name: Build and Deploy to o2switch

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: docker://node:16
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to o2switch
        uses: easingthemes/ssh-deploy@v3.0.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
          ssh-username: ${{ secrets.USERNAME }}
          server-ip: ${{ secrets.SERVER_IP }}
          local-folder: ./dist/
          remote-folder: /kitui-front/
          remote-host: ${{ secrets.SERVER_IP }}
          remote-user: ${{ secrets.USERNAME }}